lang: es
project:
  type: book

book:
  title: "Introducción a la Ecología de Poblaciones"
  author: "Jorge A. Ahumada"
  logo: owl_head.png
  repo-url: https://github.com/jaahumadap/Libro_IAEP
  chapters:
    - index.qmd
    - Prefacio.qmd
    - Introduccion.qmd
  cover-image: owl.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

