lang: es
project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Ecología de Poblaciones"
  author: "Jorge A. Ahumada"
  logo: owl_head.png
  repo-url: https://github.com/jaahumadap/Libro_IAEP
  chapters:
    - index.qmd
    - Prefacio.qmd
    - Introduccion.qmd
    - Modelos.qmd
    - Ind_Pob_Dist.qmd
    - Modelos1pob.qmd
    - Poblacion_est_edades.qmd
    - Modelos2pob.qmd
    - Metapoblaciones.qmd
  cover-image: owl.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

