# Introducción

> "Los grandes descubrimientos y mejoras invariablemente requieren de la cooperación de muchas mentes"

> -- <cite>Alexander Graham Bell (Inventor Escocés, 1847-1922)</cite>

¿Qué es la ecología de poblaciones? ¿Cuál es su papel en la biología moderna? ¿Cómo nos puede ayudar a entender y resolver los problemas ambientales que nos aquejan en la actualidad?

En contra un poco de la visión popular, la ecología es el resultado de la interacción de científicos en muchas áreas de la ciencia. Desde principios de siglo hasta el presente, la intervención de demógrafos, entomólogos, matemáticos, físicos y biólogos ha creado una disciplina donde la teoría y la práctica se mezclan de manera a veces desigual. En algunas áreas de la ecología de poblaciones se ha dado mucho más énfasis a la parte teórica y a los modelos matemáticos y se han colectado pocos datos en el campo que corroboren esta teoría y estos modelos. En otros aspectos de la disciplina existe una gran cantidad dé información empírica pero la teoría está pobremente desarrollada para unificar toda esta información. A diferencia de otras ramas de la biología y la ciencia donde la información ha sido unificada en teorías generales, la ecología hasta ahora está entrando en este proceso y en particular la ecología de poblaciones es una de las áreas en donde más rápidamente se ha avanzado al respecto.

En términos generales, la ecología de poblaciones estudia la dinámica de las poblaciones, como interactúan éstas con el ambiente que las rodea y como esta interacción origina patrones a otras escalas de organización superior como los ecosistemas y las comunidades [@Kingsland1995-ns]. La ecología de poblaciones también se centra en los individuos y en sus interacciones con el ambiente y otros individuos a través de procesos tales como la competencia la depredación, el mutualismo y el parasitismo.

Los orígenes de la ecología de poblaciones se remontan a finales del siglo pasado donde se originó también su hermana gemela, la genética de poblaciones\[\^1\].\[\^1\]: Esta sección está basada en las recopilaciones históricas de Kingsland [-@Kingsland1995-ns]. Estas disciplinas sin embargo, divergieron rápidamente por diferencias en el tipo de preguntas abordadas por cada una; la ecología de poblaciones se concentra en los cambios en el número de individuos en una población debido a cambios en el medio ambiente (biótico y abiótico). Se asume que la población es homogénea desde el punto de vista genético para simplificar los modelos.

Por otra parte, la genética de poblaciones se centra en los cambios en las frecuencias génicas de una población, asumiendo que el ambiente es constante y que las interacciones ecológicas no son importantes.

En sus primeras etapas, la ecología de poblaciones se concentra en tratar de desenredar la complejidad de las cadenas alimenticias en los ecosistemas. ¿Cómo construir generalidades a partir de las interacciones entre organismos a diferentes niveles tróficos? Este problema resulta muy complejo y los estudiosos de estas disciplinas se separan en los ahora clásicos botánicos y zoólogos. Es esta separación la que origina el estudio de las poblaciones, unidades intermedias entre la complejidad de las cadenas tróficas y el estudio del funcionamiento de los individuos (fisiología). Las fluctuaciones en las poblaciones también son de gran interés para el manejo de recursos agrícolas, precisamente en el momento en que comienza la industrialización de la agricultura en Europa y en los Estados Unidos. Este problema empieza a ser examinado por los biólogos y naturalistas empíricos quienes rápidamente empiezan a colectar información al respecto para descubrir patrones regulares en el comportamiento de las poblaciones.

Por otro lado, matemáticos, físicos y demógrafos empiezan a mostrar un interés particular en desarrollar modelos para representar matemáticamente los fenómenos que muestran las poblaciones (crecimiento, estabilidad, fluctuaciones). Las contribuciones del demógrafo Estadinense Raymond Pearl (1879-1940) al popularizar la ecuación logística de Verhulst [@Pearl1925] y los modelos del biólogo AIfred Loka (1880-1949) [@Lotka1956] y el matemático italiano Vito Volterra (1860-1940) al matematizar el problema de la competencia y la depredación [@Volterra1926], constituyen los fundamentos teóricos más importantes de la ecología de poblaciones actual. Sin embargo, los biólogos empíricos miraban con desconfianza estos modelos, ya que para ellos representaban situaciones altamente simplificadas en comparación a la complejidad del comportamiento de las poblaciones naturales.

Después de la Segunda Guerra Mundial, la ecología de poblaciones se consolida como escuela formal de la biología Sin embargo, la conexión entre teóricos y empíricos continúa débil. Debido a esta falta de comunicación la ecología entra en una crisis profunda; los empíricos alegan que los problemas poblaciones son muy complicados para poder ser entendidos con modelos sencillos. De igual manera los teóricos argumentan que necesitan de modelos más complicados y de una gran cantidad de datos para sustentar los mismos. La disciplina se empieza a orientar hacia problemas evolutivos aunque todavía lo hace de una manera muy tímida.

Hacia la década de los 60 las técnicas matemáticas se refinan y se incorpora la estadística, teoría de sistemas, teoría de información y de juegos dentro de los modelos ecológicos. Los entomólogos interesados en control biológico y los biólogos trabajando en pesquerías se concentran en modelos más realistas de dinámica poblacional basados en la ecuación logística que hace predicciones más precisas. La contribución de dos científicos estadounidenses el biólogo Alexander J. Nicholson (1895-1969) y el físico Victor Bailey (1895-1964) en los modelos de parasitismo aplicados al control biológico reflejan estas inquietudes [@Nicholson1935] . Esto obedece a problemas básicamente de índole práctico, pues existen intereses económicos de por medio. El diálogo entre la teoría y el empiricismo se abre, y la ecología se enriquece con elementos nuevos provenientes de ambas tendencias.

Hacia esta época los modelos se vuelven cada vez más complejos en el sentido de incorporar la mayor cantidad de parámetros posibles. Si el problema es complejo, es solamente cuestión de agregar más y más parámetros hasta tener una descripción más completa del problema. Estos modelos se vuelven demasiado complicados y difíciles de analizar. El modelo (en vez de la naturaleza) se vuelve el objeto de estudio. La llegada de las super-computadoras salvaría a la ecología, pensaban algunos. Los modelos llegan a una complejidad tan alta que su estudio se hace difícil no por razones científicas, sino por una limitación en el poder de cálculo de las computadoras. Los trabajos de varios ingenieros forestales en la construcción de modelos ecosistémicos modelando el comportamiento de los individuos, es un clásico ejemplo de esta tendencia [@Shugart1984].

A medida que los modelos se hacían más complejos, un biólogo y matemático Estadounidense desarrollaba una línea en la dirección contraria. Robert MacArthur (1930\~1972) argumentaba que los problemas complejos en la ecología de poblaciones se podían disectar en problemas más sencillos donde se identificaran algunos parámetros clave. Los demás parámetros únicamente agregarían "ruido" al patrón general y no debían ser considerados dentro del modelo. Los modelos de MacArthur eran muy generales, no daban predicciones numéricas precisas, pero mostraban de manera adecuada el comportamiento cualitativo de los sistemas. MacArthur termina de fusionar la ecología y la genética de poblaciones y pone toda la ecología en un contexto más histórico [@MacArthur1972].

Esta tendencia a simplificar los modelos y complementarlos con datos colectados en el campo, es la tendencia actual en la ecología de poblaciones. La pregunta clave es: ¿Qué nivel de detalle necesita el modelo para explicar lo que vemos?

Recientemente se viene dando otra revolución en la ecología de poblaciones donde los modelos son cada vez más mecanísticos. Es decir, se parte de las propiedades de los individuos para explicar el comportamiento de las poblaciones y de las comunidades. El desarrollo de nuevas técnicas estadísticas robustece la calibración de estos modelos en el campo. Ejemplos de esta nueva tendencia se ve en los trabajos de David Tilman (1949-) \[[Tilman\@1982](competencia%20basada%20en%20recursos)\] y Donald DeAngelis (1944-) y Louis Gross (1952) [@DeAngelis1992](modelos basados en el comportamiento de los individuos). La ecología está entrando en una fase excitante donde la interacción entre la teoría y el trabajo de campo la hace una disciplina menos descriptiva y más analítica y predictiva.

Este libro es un texto introductorio a la rica complejidad teórica y empírica de la ecología de poblaciones moderna. En él se pretende mostrar de manera balanceada el papel de estas dos "escuelas" de la ecología combinándolas con las tendencias más vanguardistas de la disciplina, haciendo énfasis en como podemos utilizar estas herramientas para resolver problemas ambientales concretos que nos aquejan actualmente. Pero primero, es necesario definir claramente la estructura de un modelo en ecología. Esto es central para un entendimiento claro del material presentado en este libro.
