# Nota del autor {.unnumbered}

La ecología, el estudio de las interacciones entre los organismos y su medio ambiente, es una de las áreas del saber menos entendidas por el público pero cuya popularidad ha crecido en los últimos años. Esto se debe a que en general, se asocia la ecología con el ambientalismo, los movimientos conservacionistas y la preservación del medio ambiente en general. Aunque estas actividades son importantes dentro de una sociedad como la nuestra en medio de una crisis ambiental, poco o nada tienen que ver con la ecología como ciencia. La ecología de poblaciones (la interacción entre las poblaciones y el medio ambiente) surge de la fusión de dos corrientes de conocimiento principales: un trabajo netamente teórico que comenzó hacia principios de siglo en varios sitios en Europa (principalmente Italia) y Estados Unidos y una corriente empírica desarrollada por biólogos a lo largo de todo el mundo. La ecología de poblaciones es pues una ciencia, con una bagaje teórico extenso y unos datos que los corroboran.

Sin embargo, para el estudiante de biología que quiere aprender ecología de poblaciones la teoría es un aspecto altamente obscuro y muchas veces ausente de los varios textos presentes en el mercado. Esto es culpa de una falsa idea de que la ecología debe ser enseñada sin matemáticas, pues en realidad los supuestos de los modelos casi nunca se cumplen. Esto nos ha llevado a que muchos biólogos jóvenes (y algunos no tanto) tengan una idea casi anecdótica de lo que es la ecología como ciencia sin ninguna base conceptual y teórica que la sostenga.

En los momentos de crisis ambiental en que viven actualmente varios países de América Latina, el ecólogo tiene la importante función de no sólo alertar al público y a las instituciones pertinentes de estos problemas, sino de contribuir con soluciones claras. Pero sin tener una idea clara de como aproximarse a los problemas básicos de la ecología de poblaciones y de comunidades, nuestras soluciones a muchos de ellos pueden asemejarse al ensayo y error.

Este libro surge de estas inquietudes. No existe en el mercado un libro de ecología de poblaciones en español (hay varios en inglés) que sopese la teoría y los datos empíricos de igual manera y que muestre los campos concretos donde el biólogo y el ecólogo pueden ser útiles a la sociedad. Algunos de los tópicos más importantes en la ecología de poblaciones como la depredación, herbivoría y demografía tienen aplicaciones concretas a problemas comunes en nuestras sociedades, tales como el control de plagas, el manejo óptimo de cosechas y los modelos de desarrollo sostenible. Muchos de los ejemplos mostrados vienen de las zonas tropicales del mundo y algunos vienen directamente del trabajo de campo realizado con los estudiantes durante el curso de ecología de poblaciones que dicté en la Pontificia Universidad Javeriana en Bogotá entre 1996 y 1999.

La misión principal de este libro es desmitificar el uso de los modelos matemáticos en ecología y mostrar como la interacción entre teoría y datos enriquece el conocimiento y nos ilumina sobre los procesos subyacentes en muchos de los fenómenos ecológicos que observamos en nuestros sistemas tropicales. El libro está dirigido al estudiante de pregrado en biología o ecología que por primera vez se acerca a estos temas. Sin embargo, constituye una herramienta útil al estudiante de postgrado y al profesional activo para reforzar y repasar conceptos. Es necesario haber tomado un par de cursos de cálculo y álgebra básicos para entender completamente el material expuesto en el libro. Para aquellos que no recuerdan sus matemáticas bien, he incluido un repaso general de algunos conceptos básicos en el apéndice A. Al final de cada capitulo se han incluido una serie de problemas para utilizar las herramientas discutidas en el mismo. Sugiero enfáticamente que el estudiante resuelva estos problemas a fondo para reforzar sus conocimientos.

Las siguientes personas han sido fundamentales en el desarrollo de este libro y quisiera expresarles mis agradecimientos: Andrew Dobson, Henry Horn, Simon Levin, Jon Paul Rodríguez, Luis A. Solórzano, Carlos Corredor y mi padre Jorge J. Ahumada. Después de 25 años de haber escrito esta versión, Orlando Acevedo y Andrea Morales me motivaron a crear esta nueva edición electrónica. Por último quisiera agradecer a todos los estudiantes de la Universidad Javeriana que pasaron por mi curso pues ellos fueron la fuente de inspiración última de este libro.

Jorge A. Ahumada , Agosto 2022
